const PDFDocument = require('pdfkit');
const ExcelJS = require('exceljs');
const Species = require('../models/Species');
const MonitoringSite = require('../models/MonitoringSite');
const Sighting = require('../models/Sighting');

async function getReportData(req) {
  let speciesList = [];
  let sitesList = [];
  let sightingsList = [];

  if (req.isMongoConnected) {
    speciesList = await Species.find();
    sitesList = await MonitoringSite.find();
    sightingsList = await Sighting.find().populate('species monitoringSite observedBy');
  } else {
    speciesList = req.memoryDb.species || [];
    sitesList = req.memoryDb.sites || [];
    sightingsList = req.memoryDb.sightings || [];
  }
  return { speciesList, sitesList, sightingsList };
}

exports.downloadReport = async (req, res) => {
  try {
    const { type = 'survey' } = req.query;
    const { speciesList, sitesList, sightingsList } = await getReportData(req);

    const now = new Date();
    const pad = n => String(n).padStart(2, '0');
    const ts = `${now.getFullYear()}-${pad(now.getMonth() + 1)}-${pad(now.getDate())}_${pad(now.getHours())}-${pad(now.getMinutes())}`;
    const filename = `wildlife-report-${type}-${ts}.pdf`;

    const doc = new PDFDocument({ size: 'A4', margin: 50 });
    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename="${filename}"`);
    doc.pipe(res);

    const FOREST_GREEN = '#1f4d3d';
    const MUTED = '#6b7280';
    const PAGE_BOTTOM = () => doc.page.height - doc.page.margins.bottom;

    function ensureSpace(neededHeight) {
      if (doc.y + neededHeight > PAGE_BOTTOM()) {
        doc.addPage();
      }
    }

    // Cover page
    doc.rect(0, 0, doc.page.width, doc.page.height).fill('#f5f7f4');
    doc.fillColor(FOREST_GREEN).fontSize(12).font('Helvetica-Bold').text('ECOGUARD — WILDLIFE INTELLIGENCE SYSTEM', 50, 80);
    doc.fillColor('#111827').fontSize(26).font('Helvetica-Bold').text(`REPORT: ${type.toUpperCase().replace('-', ' ')}`, 50, 200, { width: 480 });
    doc.fontSize(12).fillColor(MUTED).font('Helvetica').text(`Generated on ${now.toLocaleDateString()}`, 50, 270);
    doc.fontSize(11).fillColor('#111827').font('Helvetica-Bold').text(`Generated By: ${req.user?.name || 'Researcher'}`, 50, 295);

    doc.addPage();
    doc.fillColor(FOREST_GREEN).fontSize(18).font('Helvetica-Bold').text(`Report Overview — ${type.replace('-', ' ').toUpperCase()}`);
    doc.moveDown(1);
    doc.fillColor('#111827').fontSize(10).font('Helvetica');

    if (type === 'species-population' || type === 'executive') {
      doc.text(`Total Active Species: ${speciesList.length}`);
      doc.text(`Total Sightings: ${sightingsList.length}`);
      doc.moveDown(1);
      speciesList.forEach(sp => {
        const count = sightingsList.filter(s => (s.species?._id || s.species)?.toString() === sp._id?.toString()).length;
        ensureSpace(20);
        doc.text(`• ${sp.commonName} (${sp.scientificName}) — Status: ${sp.conservationStatus} | Sightings: ${count}`);
      });
    } else if (type === 'biodiversity') {
      doc.text(`Total Ecosystem Species Richness: ${speciesList.length}`);
      doc.text(`Total Sites Evaluated: ${sitesList.length}`);
      doc.moveDown(1);
      sitesList.forEach(st => {
        const count = sightingsList.filter(s => (s.monitoringSite?._id || s.monitoringSite)?.toString() === st._id?.toString()).length;
        ensureSpace(20);
        doc.text(`• Site ${st.siteName} (${st.habitatType}) — Sightings Logged: ${count}`);
      });
    } else if (type === 'habitat') {
      doc.text(`Total Monitoring Stations: ${sitesList.length}`);
      doc.moveDown(1);
      sitesList.forEach(st => {
        ensureSpace(25);
        doc.text(`• ${st.siteName} [${st.siteCode}] — Protected Area: ${st.protectedArea || 'N/A'} | Habitat: ${st.habitatType}`);
      });
    } else if (type === 'conservation') {
      const atRisk = speciesList.filter(sp => ['Critical', 'Vulnerable'].includes(sp.conservationStatus));
      doc.text(`High Risk Species under Watch: ${atRisk.length}`);
      doc.moveDown(1);
      atRisk.forEach(sp => {
        ensureSpace(20);
        doc.text(`⚠ ${sp.commonName} (${sp.scientificName}) — IUCN Status: ${sp.conservationStatus}`);
      });
    } else {
      // Default / survey report
      doc.text(`Total Field Records: ${sightingsList.length}`);
      doc.moveDown(1);
      sightingsList.slice(0, 15).forEach(s => {
        ensureSpace(20);
        const name = s.species?.commonName || 'Species';
        const site = s.monitoringSite?.siteName || 'Site';
        doc.text(`• ${new Date(s.eventDate || s.createdAt).toLocaleDateString()} — ${name} at ${site} (${s.individualCount || 1} count)`);
      });
    }

    const range = doc.bufferedPageRange();
    for (let i = range.start; i < range.start + range.count; i++) {
      doc.switchToPage(i);
      doc.fillColor(MUTED).fontSize(8).font('Helvetica').text(`Page ${i + 1 - range.start} of ${range.count}`, 50, doc.page.height - 40, { align: 'center' });
    }

    doc.end();
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
};

exports.downloadExcelReport = async (req, res) => {
  try {
    const { type = 'survey' } = req.query;
    const { speciesList, sitesList, sightingsList } = await getReportData(req);

    const workbook = new ExcelJS.Workbook();
    workbook.creator = 'EcoGuard Intelligence System';
    workbook.created = new Date();

    const sheet = workbook.addWorksheet(type.toUpperCase());

    if (type === 'species-population') {
      sheet.columns = [
        { header: 'Species ID', key: 'id', width: 15 },
        { header: 'Common Name', key: 'commonName', width: 25 },
        { header: 'Scientific Name', key: 'scientificName', width: 25 },
        { header: 'Category', key: 'category', width: 15 },
        { header: 'Conservation Status', key: 'status', width: 20 },
        { header: 'Total Sightings', key: 'sightings', width: 15 }
      ];
      speciesList.forEach(sp => {
        const count = sightingsList.filter(s => (s.species?._id || s.species)?.toString() === sp._id?.toString()).length;
        sheet.addRow({
          id: sp._id || sp.id,
          commonName: sp.commonName,
          scientificName: sp.scientificName,
          category: sp.category || 'Mammal',
          status: sp.conservationStatus,
          sightings: count
        });
      });
    } else if (type === 'habitat') {
      sheet.columns = [
        { header: 'Site Code', key: 'code', width: 18 },
        { header: 'Site Name', key: 'name', width: 28 },
        { header: 'Habitat Type', key: 'habitat', width: 18 },
        { header: 'Protected Area', key: 'protectedArea', width: 25 },
        { header: 'Active Status', key: 'active', width: 12 },
        { header: 'Latitude', key: 'lat', width: 15 },
        { header: 'Longitude', key: 'lng', width: 15 }
      ];
      sitesList.forEach(st => {
        sheet.addRow({
          code: st.siteCode || 'N/A',
          name: st.siteName,
          habitat: st.habitatType,
          protectedArea: st.protectedArea || 'N/A',
          active: st.active ? 'Yes' : 'No',
          lat: st.location?.latitude || 0,
          lng: st.location?.longitude || 0
        });
      });
    } else if (type === 'biodiversity') {
      sheet.columns = [
        { header: 'Site Name', key: 'name', width: 28 },
        { header: 'Total Observations', key: 'sightings', width: 20 },
        { header: 'Unique Species Count', key: 'richness', width: 20 }
      ];
      sitesList.forEach(st => {
        const siteSightings = sightingsList.filter(s => (s.monitoringSite?._id || s.monitoringSite)?.toString() === st._id?.toString());
        const uniqueSpecies = new Set(siteSightings.map(s => (s.species?._id || s.species)?.toString())).size;
        sheet.addRow({
          name: st.siteName,
          sightings: siteSightings.length,
          richness: uniqueSpecies
        });
      });
    } else if (type === 'conservation') {
      sheet.columns = [
        { header: 'Common Name', key: 'name', width: 25 },
        { header: 'Scientific Name', key: 'scientific', width: 25 },
        { header: 'IUCN Status', key: 'status', width: 20 },
        { header: 'Action Required', key: 'action', width: 50 }
      ];
      speciesList.filter(sp => ['Critical', 'Vulnerable'].includes(sp.conservationStatus)).forEach(sp => {
        sheet.addRow({
          name: sp.commonName,
          scientific: sp.scientificName,
          status: sp.conservationStatus,
          action: sp.conservationStatus === 'Critical' ? 'Increase patrol density & active telemetry monitoring' : 'Expand monitoring coverage'
        });
      });
    } else {
      // Default / survey
      sheet.columns = [
        { header: 'Sighting ID', key: 'id', width: 18 },
        { header: 'Event Date', key: 'date', width: 20 },
        { header: 'Species', key: 'species', width: 25 },
        { header: 'Site', key: 'site', width: 25 },
        { header: 'Count', key: 'count', width: 10 },
        { header: 'AI Confidence', key: 'confidence', width: 15 },
        { header: 'Verified', key: 'verified', width: 12 }
      ];
      sightingsList.forEach(s => {
        sheet.addRow({
          id: s._id || s.id,
          date: new Date(s.eventDate || s.createdAt).toLocaleString(),
          species: s.species?.commonName || 'Unknown',
          site: s.monitoringSite?.siteName || 'Unknown',
          count: s.individualCount || 1,
          confidence: `${Math.round((s.classifierConfidence || 0) * 100)}%`,
          verified: s.verified ? 'Yes' : 'No'
        });
      });
    }

    const now = new Date();
    const pad = n => String(n).padStart(2, '0');
    const ts = `${now.getFullYear()}-${pad(now.getMonth() + 1)}-${pad(now.getDate())}_${pad(now.getHours())}-${pad(now.getMinutes())}`;
    const filename = `wildlife-report-${type}-${ts}.xlsx`;

    res.setHeader('Content-Type', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
    res.setHeader('Content-Disposition', `attachment; filename="${filename}"`);

    await workbook.xlsx.write(res);
    res.end();
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
};